// Shared Tailwind color/spacing tokens for every Tailwind-CDN page.
// Single source of truth for the app's Material Design 3 "warm orange" theme.
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-fixed-variant": "#7a3000",
                "secondary-fixed-dim": "#fabd00",
                "tertiary-container": "#78a16f",
                "inverse-primary": "#ffb693",
                "on-error": "#ffffff",
                "outline": "#8c7166",
                "primary-container": "#f27024",
                "secondary-fixed": "#ffdf9e",
                "on-secondary": "#ffffff",
                "surface-container": "#f5ece7",
                "secondary": "#785900",
                "background": "#fff8f4",
                "on-tertiary": "#ffffff",
                "surface-dim": "#e0d9d3",
                "surface-container-highest": "#e9e1dc",
                "on-primary-container": "#541e00",
                "secondary-container": "#fdc003",
                "primary": "#a04100",
                "inverse-surface": "#34302c",
                "on-surface-variant": "#584238",
                "outline-variant": "#e0c0b2",
                "tertiary-fixed-dim": "#a7d29c",
                "on-primary": "#ffffff",
                "on-secondary-container": "#6c5000",
                "on-error-container": "#93000a",
                "tertiary": "#42673b",
                "surface-bright": "#fff8f4",
                "on-background": "#1e1b18",
                "surface": "#fff8f4",
                "on-secondary-fixed": "#261a00",
                "on-tertiary-fixed": "#002202",
                "surface-container-low": "#faf2ed",
                "on-primary-fixed": "#351000",
                "error": "#ba1a1a",
                "on-surface": "#1e1b18",
                "surface-container-high": "#efe7e1",
                "primary-fixed-dim": "#ffb693",
                "tertiary-fixed": "#c3eeb6",
                "error-container": "#ffdad6",
                "on-tertiary-container": "#123610",
                "on-secondary-fixed-variant": "#5b4300",
                "surface-container-lowest": "#ffffff",
                "inverse-on-surface": "#f7efea",
                "primary-fixed": "#ffdbcc",
                "surface-variant": "#e9e1dc",
                "on-tertiary-fixed-variant": "#2b4f26",
                "surface-tint": "#a04100"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-mobile": "20px",
                "gutter-mobile": "12px",
                "md": "16px",
                "base": "4px",
                "sm": "12px",
                "xs": "8px",
                "lg": "24px",
                "xl": "32px"
            }
        },
    },
}
